    versión : ' 2.1 '
    servicios :
      academia-ldap :
        imagen : osixia / openldap: 1.1.8
        medio ambiente :
          COMPOSE_HTTP_TIMEOUT : 200
          LDAP_LOG_LEVEL : " 256 "
          LDAP_ORGANISATION : " Software Architecture "
          LDAP_DOMAIN : " arqsoft.unal.edu.co "
          LDAP_BASE_DN : " "
          LDAP_ADMIN_PASSWORD : " admin "
          LDAP_CONFIG_PASSWORD : " config "
          LDAP_READONLY_USER : " falso "
          # LDAP_READONLY_USER_USERNAME: "solo lectura"
          # LDAP_READONLY_USER_PASSWORD: "solo lectura"
          LDAP_BACKEND : " hdb "
          LDAP_TLS : " verdadero "
          LDAP_TLS_CRT_FILENAME : " ldap.crt "
          LDAP_TLS_KEY_FILENAME : " ldap.key "
          LDAP_TLS_CA_CRT_FILENAME : " ca.crt "
          LDAP_TLS_ENFORCE : " false "
          LDAP_TLS_CIPHER_SUITE : " SECURE256: -VERS-SSL3.0 "
          LDAP_TLS_PROTOCOL_MIN : " 3.1 "
          LDAP_TLS_VERIFY_CLIENT : " demanda "
          LDAP_REPLICATION : " false "
          # LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn =" cn = admin, cn = config "bindmethod = credenciales simples = $ LDAP_CONFIG_PASSWORD searchbase =" cn = config "type = refreshAndPersist retry =" 60 + "timeout = 1 starttls = critical"
          # LDAP_REPLICATION_DB_SYNCPROV: "binddn =" cn = admin, $ LDAP_BASE_DN "bindmethod = credenciales simples = $ LDAP_ADMIN_PASSWORD searchbase =" $: 00: 00: 0: crítico"
          # LDAP_REPLICATION_HOSTS: "# PYTHON2BASH: ['ldap: //ldap.example.org','ldap: //ldap2.example.org']"
          LDAP_REMOVE_CONFIG_AFTER_SETUP : " true "
          LDAP_SSL_HELPER_PREFIX : " ldap "
        tty : cierto
        stdin_open : true
        volúmenes :
          - / var / lib / ldap
          - /etc/ldap/slapd.d
          - / container / service / slapd / asset / certs /
        puertos :
          - " 389: 389 "
          - " 636: 636 "
        nombre de host : " arqsoft.org "
      phpldapadmin :
        imagen : osixia / phpldapadmin: última
        container_name : phpldapadmin
        medio ambiente :
          PHPLDAPADMIN_LDAP_HOSTS : " academy-ldap "
          PHPLDAPADMIN_HTTPS : " false "
        puertos :
          - " 8085: 80 "
        enlaces :
          - academia-ldap
